### ISSUE TITLE
Protéger les données en transit

### ISSUE THREAD

**Issue by Em-AK** [jyaire/classe-royale#3]
Ajouter un certificat SSL pour rendre http://classeroyale.jejoueenclasse.fr/ accessible seulement à https://classeroyale.jejoueenclasse.fr/

Ça me semble être un prérequis avant d'ouvrir l'accès à un public plus large (ex. parents), vu que tu ne maitrisera plus les points d'accès utilisés pour se connecter à l'app (et les éventuel intermédiaires malveillants qui écoutent).

En fonction du service d'hébergement utilisé il peut y avoir des options "en un click" accessible dans l'espace d'administration pour activer le https. Sinon il y a moyen de trouver une solution avec[ letsencrypt](https://letsencrypt.org/) qui fournit des certificats gratuits.

Je peux donner un coup de main pour la mise en oeuvre si besoin.

**Comment by jyaire** [comment]
Le SSL est en place, normalement, en utilisant certbot sur le serveur. Après l'incendie sur OVH (et la perte de la base de données), j'ai tout remise à plat, et à jour, pour que je puisse relancer le projet à la rentrée.
